name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: cppcheck
      run: "sh build/cppcheck/01_cppcheck.sh"
    - name: unit
      run: "sh build/unit/02_unit.sh"
    - name: gcov
      run: "sh build/gcov/03_gcov.sh"
    - name: valgrind
      run: "sh build/valgrind/04_valgrind.sh"
    - name: valgrind-bubble
      run: "sh build/valgrind/04_valgrind_bubble.sh"
    - name: valgrind-counting
      run: "sh build/valgrind/04_valgrind_counting.sh"
    - name: valgrind-heap
      run: "sh build/valgrind/04_valgrind_heap.sh"
    - name: valgrind-insertion
      run: "sh build/valgrind/04_valgrind_insertion.sh"
    - name: valgrind-merge
      run: "sh build/valgrind/04_valgrind_merge.sh"
    - name: valgrind-quick
      run: "sh build/valgrind/04_valgrind_quick.sh"
    - name: valgrind-radix
      run: "sh build/valgrind/04_valgrind_radix.sh"
    - name: valgrind-selection
      run: "sh build/valgrind/04_valgrind_selection.sh"
    - name: sanitizer
      run: "sh build/sanitizer/05_sanitizer.sh"
    - name: sanitizer-bubble
      run: "sh build/sanitizer/05_sanitizer_bubble.sh"
    - name: sanitizer-counting
      run: "sh build/sanitizer/05_sanitizer_counting.sh"
    - name: sanitizer-heap
      run: "sh build/sanitizer/05_sanitizer_heap.sh"
    - name: sanitizer-insertion
      run: "sh build/sanitizer/05_sanitizer_insertion.sh"
    - name: sanitizer-merge
      run: "sh build/sanitizer/05_sanitizer_merge.sh"
    - name: sanitizer-quick
      run: "sh build/sanitizer/05_sanitizer_quick.sh"
    - name: sanitizer-radix
      run: "sh build/sanitizer/05_sanitizer_radix.sh"
    - name: sanitizer-radix
      run: "sh build/sanitizer/05_sanitizer_selection.sh"